### ISSUE TITLE
Wrpl Unpacker Outdated

### ISSUE THREAD

**Issue by Yay5379** [Keksilton/WtTools#10]
With the addition of rewindable replays the wrpl unpacker doesn't appear to function anymore.

**Comment by Yay5379** [comment]
This is the error message you get
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
C:\Users\Yay53\Downloads\WtTools-0.1.8.5-alpha\WtTools-0.1.8.5-alpha\WtTools.Unpacker\bin\Debug\net6.0>ls-0.1.8.5-alpha\WtTools-0.1.8.5-alpha\WtTools.Formats\BlkInfo.cs:line 213
   at WtTools.Formats.BlkInfo.ParseText(Byte[] data) in C:\Users\Yay53\Downloads\WtTools-0.1.8.5-alpha\WtTools-0.1.8.5-alpha\WtTools.Formats\BlkInfo.cs:line 148
   at WtTools.Formats.BlkInfo.ProcessData(Byte[] data) in C:\Users\Yay53\Downloads\WtTools-0.1.8.5-alpha\WtTools-0.1.8.5-alpha\WtTools.Formats\BlkInfo.cs:line 44
   at WtTools.Formats.BlkInfo..ctor(String name, Byte[] data, VromfsInfo vromfs) in C:\Users\Yay53\Downloads\WtTools-0.1.8.5-alpha\WtTools-0.1.8.5-alpha\WtTools.Formats\BlkInfo.cs:line 32
   at WtTools.Formats.WrplInfo..ctor(Byte[] data) in C:\Users\Yay53\Downloads\WtTools-0.1.8.5-alpha\WtTools-0.1.8.5-alpha\WtTools.Formats\WrplInfo.cs:line 58
   at WtTools.Unpacker.ProcessingWorker.ProcessWrpl(FileInfo file, String outputPath, CancellationToken cancellationToken) in C:\Users\Yay53\Downloads\WtTools-0.1.8.5-alpha\WtTools-0.1.8.5-alpha\WtTools.Unpacker\ProcessingWorker.cs:line 139
   at WtTools.Unpacker.ProcessingWorker.ProcessFiles(FileInfo[] files, String outputPath, CancellationToken cancellationToken) in C:\Users\Yay53\Downloads\WtTools-0.1.8.5-alpha\WtTools-0.1.8.5-alpha\WtTools.Unpacker\ProcessingWorker.cs:line 123
   at WtTools.Unpacker.ProcessingWorker.WorkerMethod(CancellationToken cancellationToken) in C:\Users\Yay53\Downloads\WtTools-0.1.8.5-alpha\WtTools-0.1.8.5-alpha\WtTools.Unpacker\ProcessingWorker.cs:line 77
   at WtTools.Unpacker.ProcessingWorker.<Start>b__53_0(Object o) in C:\Users\Yay53\Downloads\WtTools-0.1.8.5-alpha\WtTools-0.1.8.5-alpha\WtTools.Unpacker\ProcessingWorker.cs:line 54
   at System.Threading.Thread.StartCallback()
